apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: test-wal-authorization
  namespace: wal-test
  labels:
    app: wal-authorization
    env: staging
spec:
  maxUnavailable: 35%
  selector:
    matchLabels:
      app: wal-authorization
      env: staging

