apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wal-auth-v2
  namespace: wal-test
  labels:
    app: wal-auth-v2
    env: staging
spec:
  maxUnavailable: 35%
  selector:
    matchLabels:
      app: wal-auth-v2
      env: staging

