apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: wal-auth-v2-scaler
  namespace: wal-test
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: wal-auth-v2
  minReplicaCount: 2
  maxReplicaCount: 6
  cooldownPeriod: 300
  advanced:
    horizontalPodAutoscalerConfig:
      name: wal-auth-v2
  triggers:
  - type: memory
    metricType: Utilization
    metadata:
      value: "70"
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"

